SCREEN_WIDTH = 400
SCREEN_HEIGHT = 400

RESOURSES_PATH = "./resourses/"
MODELS_PATH = RESOURSES_PATH + "models/"
MAPS_PATH = RESOURSES_PATH + "maps/"

COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
