SCREEN_WIDTH = 400
SCREEN_HEIGHT = 400

HALF_SCREEN_WIDTH = SCREEN_WIDTH // 2
HALF_SCREEN_HEIGHT = SCREEN_HEIGHT // 2

FULLSCREEN = False

RESOURSES_PATH = "./resourses/"
MODELS_PATH = RESOURSES_PATH + "models/"
MAPS_PATH = RESOURSES_PATH + "maps/"

COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)

PLAYER_VELOCITY = 0.005
